/**
 * uImposition runtime configuration.
 * Все изменяемые производственные значения находятся здесь.
 * All editable production values are centralized here.
 */
export const CONFIG = Object.freeze({
  app: {
    name: "uImposition",
    defaultLanguage: "ru",
    supportedLanguages: ["ru", "en"],
    unit: "mm",
  },

  sheetPresets: [
    { id: "616x446", label: "616 × 446", width: 616, height: 446, sizeStage: "afterTrim" },
    { id: "616x466", label: "616 × 466", width: 616, height: 466, sizeStage: "afterTrim" },
    { id: "636x448", label: "636 × 448", width: 636, height: 448, sizeStage: "afterTrim" },
    { id: "646x466", label: "646 × 466", width: 646, height: 466, sizeStage: "afterTrim" },
    { id: "650x313", label: "650 × 313", width: 650, height: 313, sizeStage: "afterTrim" },
    { id: "716x326", label: "716 × 326", width: 716, height: 326, sizeStage: "afterTrim" },
    { id: "716x336", label: "716 × 336", width: 716, height: 336, sizeStage: "afterTrim" },
    { id: "716x516", label: "716 × 516", width: 716, height: 516, sizeStage: "afterTrim" },
  ],

  productPresets: [
    { id: "A4", label: "A4 — 210 × 297", width: 210, height: 297 },
    { id: "A5", label: "A5 — 148 × 210", width: 148, height: 210 },
    { id: "A6", label: "A6 — 105 × 148", width: 105, height: 148 },
  ],

  bleedPresetsMm: [0, 2, 5],

  defaults: {
    sheetPresetId: "custom",
    sheetWidth: 620,
    sheetHeight: 450,
    sizeStage: "beforeTrim",
    trimEnabled: true,
    trimUniform: true,
    trimUniformMm: 2,
    trimSidesMm: { left: 2, right: 2, top: 2, bottom: 2 },
    pressMarginsMm: { left: 4, right: 4, top: 2, bottom: 13 },
    productPresetId: "A6",
    productWidth: 105,
    productHeight: 148,
    productBleedMm: 0,
    spacingMode: "commonCut",
    productGapMm: 0,
    ordersText: "",
  },

  limits: {
    minDimensionMm: 1,
    maxDimensionMm: 2000,
    minTrimMm: 0,
    maxTrimMm: 50,
    minPressMarginMm: 0,
    maxPressMarginMm: 100,
    minProductDimensionMm: 1,
    maxProductDimensionMm: 1000,
    minBleedMm: 0,
    maxBleedMm: 20,
    minGapMm: 0,
    maxGapMm: 100,
    maxOrders: 500,
    maxPagesPerFile: 10000,
    maxQuantity: 100000000,
    maxPreviewCells: 200,
    maxPagePairRows: 500,
    decimalStepMm: 0.1,
  },

  storage: {
    projectKey: "uImposition.m2.project",
    languageKey: "uImposition.language",
    persistPanelCollapsedState: false,
  },

  demo: {
    queryParameter: "demo",
    controlCaseUrl: "./data/control-case.json",
    controlLayoutUrl: "./data/control-layout-m3.json",
  },

  pdf: {
    defaultPageMode: "a4",
    supportedPageModes: ["a4", "sheetProportional", "custom"],
    a4: { widthMm: 210, heightMm: 297 },
    defaultMarginMm: 10,
    preserveAspectRatio: true,
    safeNameDigits: 2,
    renderDpi: 180,
    jpegQuality: 0.92,
    proportionalLongSideMm: 297,
    canvasFontFamily: "Arial, 'DejaVu Sans', sans-serif",
    schemeDocumentFileName: "uImposition-schemes.pdf",
    reportDocumentFileName: "uImposition-production-report.pdf",
  },

  optimizer: {
    candidateGeneration: {
      minDistinctPairs: 1,
      maxDistinctPairs: 2,
      maxCandidates: 10000,
      idPrefix: "AUTO",
    },
    decision: {
      defaultObjectiveOrder: [
        "physicalSheets",
        "layoutForms",
        "colorPlates",
        "fileOverrun",
        "pairOverrun",
        "pressPasses",
        "splitOrders",
        "impositionCount",
        "layoutCompactness",
        "distinctOrdersPerImposition",
      ],
      hardConstraints: [
        "zeroUnderproduction",
        "validPrintableGeometry",
        "validFrontBackMapping",
        "validOrientation",
        "validDuplexStrategy",
        "validatedProductionReport",
      ],
    },
  },

  i18n: {
    ru: {
      customPreset: "Произвольный размер",
      customProduct: "Произвольный формат",
      beforeTrim: "Размер до зачистки",
      afterTrim: "Размер уже после зачистки",
      noOrders: "Заказы пока не введены",
      orderCount: "Файлов",
      printPairCount: "Печатных пар",
      totalQuantity: "Сумма тиражей",
      invalidInput: "Проверьте выделенные поля",
      stageAfterTrimHint: "Этот пресет уже указан после зачистки. Повторное уменьшение не применяется.",
      stageBeforeTrimHint: "Из исходного размера будут вычтены значения зачистки.",
      commonCutHint: "Общий рез применяется только при выпуске 0 мм.",
      separatedHint: "Сначала учитывается выпуск, затем дополнительный зазор между границами выпусков.",
      loadedControlCase: "Контрольный набор загружен",
      loadFailed: "Не удалось загрузить контрольный набор",
      fits: "Изделие помещается",
      doesNotFit: "Изделие не помещается",
      rows: "рядов",
      columns: "колонок",
      positions: "позиций",
      noPairs: "Введите заказы, чтобы увидеть пары страниц.",
    },
    en: {
      customPreset: "Custom size",
      customProduct: "Custom product size",
      beforeTrim: "Size before sheet trim",
      afterTrim: "Size already after trim",
      noOrders: "No orders entered yet",
      orderCount: "Files",
      printPairCount: "Print pairs",
      totalQuantity: "Total run length",
      invalidInput: "Check the highlighted fields",
      stageAfterTrimHint: "This preset is already post-trim. No second trim reduction is applied.",
      stageBeforeTrimHint: "The configured trim values will be subtracted from the source sheet.",
      commonCutHint: "Common cut is valid only with 0 mm bleed.",
      separatedHint: "Bleed is applied first, followed by the additional gap between bleed boundaries.",
      loadedControlCase: "Control dataset loaded",
      loadFailed: "Could not load the control dataset",
      fits: "Product fits",
      doesNotFit: "Product does not fit",
      rows: "rows",
      columns: "columns",
      positions: "positions",
      noPairs: "Enter orders to display page pairs.",
    },
  },
});
